version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Adjust according to your project requirements
    commands:
      - echo "Installing Amplify CLI..."
      - npm install -g @aws-amplify/cli
      - npm install
      - echo "Configuring AWS CLI..."

      - aws configure set region "us-east-1"  # Adjust region if needed

  build:
    commands:
      - echo "Pulling Amplify environment..."
      - amplify pull --appId d2o0qumi8rq9fb --envName main --yes
      - npm run build

  post_build:
    commands:
      - echo "Deploying to Amplify..."
      - amplify push --yes

artifacts:
  baseDirectory: dist  # Ensure this is correct for your project output folder
  files:
    - '**/*'

cache:
  paths:
    - node_modules/**/*  # Cache node_modules to reuse dependencies



# version: 0.2
# backend:
#   phases:
#     build:
#       commands:
#         - '# Execute Amplify CLI with the helper script'
#         - amplifyPush --simple
# frontend:
#   phases:
#     preBuild:
#       commands:
#         - yarn install --frozen-lockfile
#     build:
#       commands:
#         - yarn run build
#   artifacts:
#     baseDirectory: dist
#     files:
#       - '**/*'
#   cache:
#     paths:
#       - node_modules/**/*
