version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing AWS CLI if not already installed..."
      - if aws --version; then echo "AWS CLI is already installed."; else 
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip";
        unzip awscliv2.zip; 
        sudo ./aws/install;
        fi
      - aws --version

  pre_build:
    commands:
      - echo "Fetching secrets from AWS Secrets Manager..."
      - SECRETS=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:us-east-1:211125344531:secret:aws-cred-IsEPiR --query SecretString --output text)
      - export AWS_ACCESS_KEY_ID=$(echo $SECRETS | jq -r '.AWS_ACCESS_KEY_ID')
      - export AWS_SECRET_ACCESS_KEY=$(echo $SECRETS | jq -r '.AWS_SECRET_ACCESS_KEY')
      - echo "Secrets retrieved and environment variables set."

  build:
    commands:
      - echo "Using retrieved AWS credentials..."
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - aws configure set region us-east-1  # Change to your preferred AWS region
      - echo "AWS credentials configured successfully."

artifacts:
  baseDirectory: dist
  files:
    - '**/*'

cache:
  paths:
    - node_modules/**/*






# version: 0.2
# backend:
#   phases:
#     build:
#       commands:
#         - '# Execute Amplify CLI with the helper script'
#         - amplifyPush --simple
# frontend:
#   phases:
#     preBuild:
#       commands:
#         - yarn install --frozen-lockfile
#     build:
#       commands:
#         - yarn run build
#   artifacts:
#     baseDirectory: dist
#     files:
#       - '**/*'
#   cache:
#     paths:
#       - node_modules/**/*
