version: 0.2  

phases:  
  install:  
    runtime-versions:  
      nodejs: 18  # Adjust according to your project requirements  
    commands:  
      - echo "Checking AWS CLI installation..."  
      - if aws --version; then echo "AWS CLI is already installed, skipping installation."; else  
          echo "Installing AWS CLI...";  
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip";  
          unzip awscliv2.zip;  
          sudo ./aws/install;  
          fi  
      - aws --version  # Verify AWS CLI version  

      - echo "Installing Amplify CLI..."  
      - npm install -g @aws-amplify/cli  
      - npm install  

      - echo "Setting AWS credentials..."  
      - aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"  
      - aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"  
      - aws configure set region us-east-1  # Change to your AWS region  

      - echo "Pulling Amplify environment..."  
      - amplify pull --appId d3nwx8ygwkxq9g --envName main --yes --profile default || echo "Amplify pull failed"  

      - echo "Building the project..."  
      - npm run build  

  post_build:  
    commands:  
      - echo "Deploying to Amplify..."  
      - aws amplify start-job --app-id d3nwx8ygwkxq9g --branch-name main --job-type RELEASE


artifacts:  
  files:  
    - '/*'  # Include all files in the artifacts

