version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Adjust according to your project requirements
    commands:
      - echo "Checking AWS CLI installation..."
      - if aws --version; then echo "AWS CLI is already installed, skipping installation."; else 
        echo "Installing AWS CLI..."; 
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"; 
        unzip awscliv2.zip; 
        sudo ./aws/install; 
        fi
      - aws --version  # Verify AWS CLI version
      - echo "AWS_ACCESS_KEY_ID is $AWS_ACCESS_KEY_ID"
      - echo "AWS_SECRET_ACCESS_KEY is $AWS_SECRET_ACCESS_KEY"
      - echo "AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY are set."
      # Use the environment variables to authenticate or configure services as needed

artifacts:
  baseDirectory: dist
  files:
    - '**/*'

cache:
  paths:
    - node_modules/**/*  # Cache node_modules to reuse dependencies
